name: Check node version
on:
  push:
    branches:
      - master 
jobs:
  check-version-of-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: '14'
      - run: npm install
      - run: node -v
