name: CI to Docker Hub
on: 
  push: 
    branches: [ master ]
jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SEVER_HOST }}
          key: ${{ secrets.SEVER_TOKEN }}
          username: ${{ secrets.SEVER_USERNAME }}

          script: |
            echo "Login succesfull"


