name: Build project
on:
  push:
    branches:
      - master 
jobs:
  check-version-of-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '14'
      - name: npm install and generate
        run: |
          npm install
          npm run build
          npm run generate 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md 
      - name: Download dist folder
        uses: actions/download-artifact@v2
        with:
          name: dist 
