name: CD to Server
on: 
  push: 
    branches: [ master ]
jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}

          script: |
            echo "Login succesfull"
            git clone git@github.com:Khemy543/SMP.git
            cd SMP
            npm install
            npm run generate
            sudo cp -R dist/* /var/www/html/admin.smp.com 
            cd ~
            sudo rm -rf SMP 

